.\" Copyright (c) 2019 Camille Moncelier <camille@moncelier.fr>
.\"
.\" Permission to use, copy, modify, and/or distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd May 29, 2019
.Dt SYSRQ-FIREFOX 4
.Os
.Sh NAME
.Nm sysrq-firefox
.Nd A Sysrq for killing Firefox (Don't Ask...)
.Sh SYNOPSIS
.Nm Alt-PrintScreen-x : Kill Firefox (MainThread)
.Sh DESCRIPTION
A Sysrq for killing Firefox (Don't Ask...)
.El
.Sh AUTHORS
.An -nosplit
The
.Nm
program was written by
.An Camille Moncelier Aq camille@moncelier.fr .
